services:
  php:
    build: .
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    environment:
      - APP_ENV=development

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
