services:
  app:
    build: .
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    environment:
      - APP_ENV=development
    expose:
      - "9000" # Expose port 9000 for PHP-FPM to the internal network

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
