app_index:
    path:     /
    controller: App\UI\Controller\IndexController
    method: execute

app_show:
    path:     /show/{id}
    controller: App\UI\Controller\PostController
    method: execute